### PR TITLE
Add colspecs for mySQL date, time and datetime types

### PR DESCRIPTION
**Pull request by olinger**
This will parse date/time/datetimes as equivalent python objects in mysql instead of strings.

### CODE REVIEW

**Comment by augeas** [comment]
This is a much-needed feature.

**Comment by olinger** [comment]
I've resolved the conflicts in this branch. Any thoughts on getting it merged, or feedback on what you'd like changed?

**Comment by micduffy** [comment]
Yes please can someone merge this ? It is much needed for our project. Thanks for the great work

**Comment by kislyuk** [comment]
Apologies all for being terribly late in merging this. I definitely neglected this PR for too long.  Released in v0.2.1, please test.

**Comment by micduffy** [comment]
Thanks so much ! Will let u know if any issues

**Pull request merged**
